apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "quarkus.fullname" $ }}-configmap-env"
  labels:
    {{- include "quarkus.labels" $ | nindent 4 }}
data:
  application.mode: {{ .Values.mode }} 
